### ISSUE TITLE
I2C sniffer - information request

### ISSUE THREAD

**Issue by samtal** [rricharz/i2c-sniffer-100kBaud-Arduino-Mega#1]
Hello Rene,
To monitor I2C traffic I was looking for a basic core tool and found your one that, looking into its details,  seems to be the right solution.
Nevertheless, to be sure, can you please add a few words about the hardware connection details?
Do you connect the SDA to SDA and SCL to CLS directly on the line, or add a buffer?  
Another issue: Your program defines:
#define SDA    0x80
#define SCL     0x40  
which contradicts the common header pins_arduino.h: (**and cause compilation error**)
static const uint8_t SDA = 20;
static const uint8_t SCL = 21; 

Can you please elaborate on the actual connection and defines?
Thanks,
samtal

**Comment by rricharz** [comment]
Hello samdal,

This tool works only on a Arduino Mega, which was selected because of the RAM size. It does not use the standard i2c pins, but pin 30 and pin 31 of the Mega (reason explained below):
#define SDA               0x80                        // Pin 30 (PC7) on PINC is used for the SDA line
#define SCL               0x40                         // Pin 31 (PC6) on PINC is used for the SCL line

The way it works is that you have an existing i2c connection with a master and a slave, and you want to sniff the traffic on this connection. The master should NOT be the MEGA, on which this tool is running! What you do is that you leave the existing connection between master and slave running, and just connect the SDA and SCL lines of this i2c connection also to the Arduino Mega, pin 30 and 31. You also need to connect the GROUND. While the master and slave are now talking to each other, you can sniff this communication with the Arduino Mega.

Because the Arduino Mega does not interfere with the existing i2c bus (pin 30 and 31 are set to input), you can sniff both 3.3V and 5V logic i2c lines, and you see what really happens on the bus, even if the Mega would not be connected. I used the tool to sniff the i2c bus between a Raspberry Pi and a connected slave. This is also one of the reasons why the tool does not use the standard i2c pins of the Arduino. As far as I know these are pulled up to 5 V by pullup resistors and sniffing a connection with a 3.3V device would potentially destroy the i2c pins of this device.

The way the tool works îs that it first just record all logical transitions (from 1 to 0 or from 0 to 1) of the two i2c lines). For speed reasons these are just stored. The tooldisplays the raw data and analyzes it afterwards once the recording has been finished.

I hope this helps.
If you have more questions, please feel free to ask.

Rene

**Comment by samtal** [comment]
Thanks Rene for your prompt and detailed reply, 
Yes, I use an independent Mega2560 directly connected to the line between my original Mega master and the slave device (A commercial power supply controled by I2C, SDA and SCL + Gnd).
I now connected the SCL and SDA to pins 30, 31, but in order to make it really work I had to remove (out-comment) the defines, and add in the Setup: (To override the Arduino persistent defaults and enable compilation)
////////////
void setup()
////////////
{
  Serial.begin(115200);
  Serial.println("\ni2c sniffer by rricharz\n");
**//Overriding the Arduino defaults:
  const uint8_t SDA = 0x80;    //pin 30
  const uint8_t SCL = 0x40;      //pin31** 

 int points = acquire_data();
  display_data(points);
}

I will now try to analyze the data according to my expected I2C protocol, and will write a special parser to convert to readable language, assuming the data is reasonably persistent. 
I will naturally keep you informed on the results, but it may take some time.
Thanks again for your support.   
samtal

**Comment by samtal** [comment]
Example of my initial raw data:
[i2c sniffer by rricharz samtal test.txt](https://github.com/rricharz/i2c-sniffer-100kBaud-Arduino-Mega/files/478115/i2c.sniffer.by.rricharz.samtal.test.txt)
samtal

**Comment by rricharz** [comment]
I will look into why you got the compiler error. I used Arduino 1.6.9. Maybe the constants could be renamed to, for example SDA_MASK und SCL_MASK to avoid the conflict. I will update the code accordingly.

I cannot say much about your raw data without knowing details about the device and what has to be expected. In my case the host was talking to a bq40z60 from TI. I got the manual from the TI web page and was then able to understand what was transferred on the bus and why. It would probably also makes sense to decode the raw data on a pc or mac instead of doing that directly on the Arduino.

The individual blocks you aquire are similar, but not identical. I wonder whether this has to be expected in your case or whether there is a problem (clock speed too fast, i2c lines noisy, pull ups wrong etc). A scope might help in this case.

Thanks for your feedback.

**Comment by samtal** [comment]
Hi Rene,
Sorry for the long delay in my reply, but I am busy with too many projects, and had to put this one aside for a while.
As I need a real-time tool (data out per each message, including parsing. I have sufficient time between my 40-100 mSec messages), I will try to modify the program to run continuously rather than a one-time shot mode.
It may take some time, but I will update you once I make progress.
Thanks again,
samtal

**Comment by rricharz** [comment]
Hi Samdal,
I have modified the program to run now continuously. This means that TIMEOUT needs to be adjusted based on the actual activity on the i2c bus. Details on how to do it are in the source and the description. In your case TIMEOUT should probably be set to somewhat above 100 msec. I have also commented out the display of the raw data, but it is still there if you need it.
Thanks for your input.
Rene
